dbfilename redis_cache.rdb
dir /home/lenovo/edu-bench/config/pids
pidfile /home/lenovo/edu-bench/config/pids/redis_cache.pid
bind 127.0.0.1
port 13006
maxmemory 141mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /home/lenovo/edu-bench/config/redis_cache.acl
